repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        description: "Run 'prettier' for JavaScript formatting"
        entry: just format
        language: system
        types_or: [ts, tsx, jsx]
        pass_filenames: false
        require_serial: true
      - id: eslint
        name: eslint
        description: "Run 'eslint' for JavaScript linting"
        entry: just lint
        language: system
        types_or: [ts, tsx, jsx]
        pass_filenames: false
        require_serial: true
